# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='admin', max_length=250, verbose_name='Author'),
        ),
    ]
